# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_auto_20160125_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('id_modelo', models.PositiveSmallIntegerField()),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('relacionado', models.CharField(max_length=50)),
                ('id_relacionado', models.PositiveSmallIntegerField()),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
