# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(default='nada'),
            preserve_default=False,
        ),
    ]
