# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20160125_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagorecibo',
            options={'verbose_name': 'Pago de Recibo', 'verbose_name_plural': 'Pago de Recibos'},
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='precio',
            field=models.PositiveSmallIntegerField(blank=True, default=30000, null=True),
        ),
    ]
