# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_auto_20160126_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagorecibo',
            old_name='cuenta',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='pagorecibo',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='precio',
        ),
        migrations.AlterField(
            model_name='pagorecibo',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 1, 26, 14, 18, 3, 319424, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
