# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 04:50
from __future__ import unicode_literals

import apps.comercios.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rif', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.TextField()),
                ('foto_perfil', models.ImageField(blank=True, upload_to='comercios')),
                ('foto_portada', models.ImageField(blank=True, upload_to='comercios')),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('descripcion_corta', models.TextField(max_length=140)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, validators=[apps.comercios.models.validar_positivo])),
                ('stock', models.PositiveSmallIntegerField()),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('visitas', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('Comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto_Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto0', models.ImageField(blank=True, upload_to='productos', verbose_name='1ra Foto')),
                ('foto1', models.ImageField(blank=True, upload_to='productos', verbose_name='2da Foto')),
                ('foto2', models.ImageField(blank=True, upload_to='productos', verbose_name='3ra Foto')),
                ('foto3', models.ImageField(blank=True, upload_to='productos', verbose_name='4ta Foto')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto')),
            ],
            options={
                'verbose_name': 'Fotos del Producto',
                'verbose_name_plural': 'Fotos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto_Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=120)),
                ('puntaje', models.PositiveSmallIntegerField(default=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto')),
            ],
            options={
                'verbose_name': 'Opinion sobre Producto',
                'verbose_name_plural': 'Opiniones sobre Productos',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_pub', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Publicacion_Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_pub', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Publicacion')),
            ],
            options={
                'verbose_name': 'Comentario en Publicacion',
                'verbose_name_plural': 'Comentarios en Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Publicacion_Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto'),
        ),
    ]
