# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='area_interes',
            field=models.ManyToManyField(to='administrativo.Area_Interes'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='parroquia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Parroquia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comercio',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='area_interes',
            field=models.ManyToManyField(to='administrativo.Area_Interes'),
        ),
        migrations.AddField(
            model_name='publicacion_comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
