# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20160114_0025'),
        ('comercios', '0002_auto_20160114_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto_Pregunta')),
            ],
        ),
    ]
