# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_producto_pregunta_producto_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_respuesta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comercios.Producto'),
            preserve_default=False,
        ),
    ]
