# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
        ('comercios', '0004_producto_respuesta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='agencias',
            field=models.ManyToManyField(to='administrativo.Agencia'),
        ),
    ]
