# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0005_comercio_agencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio_Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=4)),
                ('telefono', models.CharField(max_length=7)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio')),
            ],
        ),
    ]
