# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0007_remove_comercio_agencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio_telefono',
            name='prefijo',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='comercio_telefono',
            name='telefono',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
