# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0008_auto_20160123_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='foto_perfil',
            field=models.ImageField(upload_to='comercios'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='foto_portada',
            field=models.ImageField(upload_to='comercios'),
        ),
        migrations.AlterField(
            model_name='comercio_telefono',
            name='prefijo',
            field=models.CharField(choices=[('0246', '0246'), ('0412', '0412'), ('0416', '0416'), ('0426', '0426'), ('0424', '0424'), ('0414', '0414')], max_length=4),
        ),
    ]
