# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20160123_2235'),
        ('comercios', '0010_auto_20160126_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio_Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=120)),
                ('puntaje', models.PositiveSmallIntegerField(default=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio')),
            ],
            options={
                'verbose_name': 'Opinion sobre Comercio',
                'verbose_name_plural': 'Opiniones sobre Comercios',
            },
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='publicacion_promocion',
            name='publicacion',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='Publicacion_Promocion',
        ),
    ]
