# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_auto_20160126_2202'),
        ('comercios', '0012_auto_20160307_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='area_interes',
            field=models.ManyToManyField(to='administrativo.Area_Interes'),
        ),
    ]
