# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0013_publicacion_area_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('nro_cuenta', models.CharField(max_length=20)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], default='corriente', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comercio',
            name='cuenta',
            field=models.ManyToManyField(to='comercios.Cuenta_Banco'),
        ),
    ]
