# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 04:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativo', '0001_initial'),
        ('comercios', '0002_auto_20160114_0020'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='area_interes',
            field=models.ManyToManyField(blank=True, to='administrativo.Area_Interes'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parroquia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Parroquia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente_seguir',
            name='comercio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='comercio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra_envio',
            name='agencia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Agencia'),
            preserve_default=False,
        ),
    ]
