# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_compra_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_pago',
            name='banco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra_pago',
            name='cuenta',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra_pago',
            name='nro_referencia',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
