# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20160114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='envio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Compra_Envio'),
        ),
        migrations.AlterField(
            model_name='compra_envio',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
