# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20160114_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_envio',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Agencia'),
        ),
    ]
