# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20160114_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra_pago',
            name='tipo_pago',
            field=models.CharField(choices=[('deposito', 'Deposito'), ('trans', 'Transferencia')], default='trans', max_length=50),
        ),
    ]
