# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20160115_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_seguir',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to='comercios.Comercio'),
        ),
    ]
