# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20160123_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_seguir',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercios.Comercio'),
        ),
    ]
